# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "first lane to test"
  lane :spendly do
    sh "flutter clean"
    sh "flutter build apk --release -t lib/main_prod.dart --flavor production --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:295153944238:android:15f33beb88a2fb7b04cf3f",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "ma7080642@gmail.com",
      release_notes: "first release of the app",
    )
  end
end
